config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "article#index"
  get '/article/index'
  get '/article/new'
  get '/article/show'
  get '/article/edit'
  get '/article/list'
  post 'create' => 'article#create'
  # put '/update', to: 'article#update'
  patch 'update' => 'article#update'
  delete '/article/delete'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
    # GET /article/index/
    def index
    end

    # GET /article/list/
    def list
        @articles = Article.all
    end

    # GET /article/new/
    def new
        @article = Article.new
    end

    # POST /article/create/
    def create
        @article = Article.new(article_params)
        if @article.save
            redirect_to article_index_path
        else
            redirect_to article_new_path
        end
    end

    # GET /article/edit/
    # fetch data in perticular id (by => :id)
    def edit
        @article = Article.find(params[:id])
    end

    # PUT/PATCH /article/update/
    # update the given data in particular id (by => :id)
    def update
        @article = Article.find(params[:id])
        @article.update(article_params)
        redirect_to article_index_path
    end

    # DELETE /article/delete/
    # destory or delete the perticular data (by => :id)
    def delete
        @article = Article.find(params[:id])
        @article.destroy
        redirect_to article_index_path
    end

    # GET /article/show/
    # fetch data in perticular id (by => :id)
    def show
        @article = Article.find(params[:id])
    end

    private
    # it's only allow a list of parameters
    def article_params
        params.require(:article).permit(:title,:content,:author)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/views/article/_navbar.html.erb
<style>
    body{
        background-color: rgb(144, 144, 144);
    }
    .navbar{
        width: 100%;
        position: fixed;
        z-index: 100;
        /* padding-bottom: 30px; */
    }
    ul{
        margin: 0px;
        background-color: rgb(255,255,255);
        /* margin-bottom: 30px; */
        display: block;
        padding: 15px;
    }
    ul li{
        padding-left: 10px;
        padding-right: 10px;
    }
    a{
        color: black;
        text-decoration: none;
        font-weight: bolder;
        font-size: larger;
    }
</style>
<div class="navbar">
    <ul>
        <li style="display: inline;">
            <a href="/article/index/" style="padding-left: 10px; ">Home</a>
        </li>
        <li style="display: inline;">
            <a href="/article/list/" style="padding-left: 10px;">Article</a>
        </li>
    </ul>
</div>
<br><br>

app/views/article/edit.html.erb
<style>
    h1{
        text-align: center;
    }
    .container{
        width: 100%;
        display: flex;
        text-align: left;
        justify-content: center;
        align-items: center;
    }
    .data{
        /* width: 380px; */
        display: inline;
        background-color: rgb(210,210,210);
        padding: 5px;
        border: 1px solid black;
        border-radius: 12px;
    }
    label{
        padding: 5px;
        font-weight: bold;
    }
    .text_area{
        margin: 0px 20px;
    }
    .btn{
        display: flex;
        justify-content: space-around;
        padding: 4px;
        align-items: center;
    }
    .btn input{
        height: 35px;
        padding: 8px;
        border-radius: 8px;
        border: 0.8px solid black;
        font-weight: bold;
        background-color: aliceblue;
        font-size: 12px;
    }
    .btn p{
        background-color: aliceblue;
        border: 0.8px solid black;
        border-radius: 8px;
        display: inline;
        padding: 8px;
        font-weight: bold;
        font-size: 12px;
        height: 15px;
    }
</style>


<h1>Update Article</h1>

<div class="container">
<div class="data">
    <%= form_for @article, :url => {:action => 'update', :id => @article.id} do |field| %>
<p>
    <label for="">Title : </label>
    <%= field.text_field 'title' %>
</p>
<p>
    <label for="">Author : </label>
    <%= field.text_field 'author' %>
</p>
<p>
    <label for="">Content : </label>
    <div class="text_area">
        <%= field.text_area 'content', size: "40x10" %>
    </div>
</p>
<div class="btn">
    <p>
        <%= link_to "Back", article_list_path %>
    </p>
    <%= submit_tag 'Submit' %>
    <% end %>
</div>
</div>
</div>

app/views/article/index.html.erb
<style>
    h1{
        text-align: center;
    }
    .new{
        display: flex;
        margin-left: 30px;
    }
    .new p{
        border: 0.8px black solid;
        border-radius: 8px;
        padding: 8px;
        display: inline;
        background-color: aliceblue;
    }
    .list{
        margin-left: 30px;
        display: flex;
    }
    .list p{
        border: 0.8px black solid;
        border-radius: 8px;
        padding: 8px;
        display: inline;
        background-color: aliceblue;
    }
    .btn{
        justify-content: center;
        display: flex;
    }
</style>

<h1>Blog Article's</h1>
<div class="btn">
    <div class="new">
        <p>
            <%= link_to "New Article", article_new_path %>
        </p>
    </div>
    <div class="list">
        <p>
            <%= link_to "Article's", article_list_path %>
        </p>
    </div>
</div>

app/views/article/list.html.erb
<style>
    ::-webkit-scrollbar{
        display: none;
    }
    h1{
        font-weight: bold;
        text-align: center;
        justify-content: center;
        /* background-color: indigo; */
        margin: 0;
        padding: 15px;
    }
    .blog{
        display: grid;
        /* width: 100%; */
        grid-template-columns: repeat(6, 220px);
        grid-column-gap: 30px;
        grid-row-gap: 25px;
        /* background-color: indigo; */
        padding: 10px;
    }

    .article{
        padding: 10px 0px;
        width: 220px;
        background-color: rgb(210, 210, 210);
        display: grid;
        border-radius: 12px;
        margin: 12px;
        box-shadow: 5px 5px 5px 2px slategrey;
        border: 1px solid black;        
    }
    .article h2{
        text-align: center;
        justify-content: center;
    }
    .article p{
        text-align: center;
    }
    .btn{
        display: flex;
        height: 20px;
        align-items: center;
        justify-content: space-around;
        margin: 15px 0px;
    }
    .btn p{
        font-size: 10px;
        display: inline;
        padding-left: 15px;
        padding-right: 15px;
        background-color: aliceblue;
        border-radius: 12px;
        padding-top: 3px;
        padding-bottom: 3px;
        border: 0.4px solid black;
    }
    .btn p a{
        color: black;
    }
    .btn-back{
        display: inline;
        padding: 15px;
        margin: 10px;
        padding-bottom: 40px;
    }
    .btn-add{
        display: inline;
        padding: 15px;
        margin: 10px;
        padding-bottom: 40px;
    }
    .btn-back p{
        font-size: 12px;
        display: inline;
        border: 1.5px solid black;
        border-radius: 5px;
        padding: 8px;
        background-color: aliceblue;
    }
    .btn-add p{
        font-size: 12px;
        display: inline;
        border: 1.5px solid black;
        border-radius: 5px;
        padding: 8px;
        background-color: aliceblue;
    }
    .none{
        text-align: center;
    }
    .btn1{
        justify-content: center;
        padding: 15px;
        display: flex;
        /* align-items: center; */
    }
</style>


<h1>Article's</h1>
<% if @articles.empty? %>
<div class="none">
    <p>There is no blog article's.</p>
</div>
<div class="btn1">
    <div class="btn-add">
        <p>
            <%= link_to "Add", article_new_path %>
        </p>
    </div>
    <div class="btn-back">
        <p>
            <%= link_to "Back", article_index_path %>
        </p>
    </div>
</div>
<% else %>
<div class="blog">
    <% @articles.each do |d| %>
    <div class="article">
        <h2><%= d.title.capitalize %></h2>
        <p>Author : <%= d.author.capitalize %></p>
        <div class="btn">
            <p><%= link_to "Read", {:action => 'show',:id => d.id} %></p>
            <p><%= link_to "Delete",{:action => 'delete',:id => d.id},data: {'turbo-method': :delete}%></p>
        </div>
    </div>
    <% end %>
</div>
<br><br>
<div class="btn1">
    <div class="btn-back">
        <p>
            <%= link_to "Back", article_index_path %>
        </p>
    </div>
</div>
<%end%>

app/views/article/new.html.erb
<style>
    h1{
        text-align: center;
    }
    .container{
        width: 100%;
        display: flex;
        text-align: left;
        justify-content: center;
        align-items: center;
    }
    .form{
        /* width: 380px; */
        display: inline;
        background-color: rgb(210,210,210);
        padding: 5px;
        border: 1px solid black;
        border-radius: 12px;
    }
    label{
        padding: 5px;
        font-weight: bold;
    }
    .text_area{
        margin: 0px 20px;
    }
    .btn_submit{
        display: flex;
        justify-content: space-around;
        padding: 4px;
        align-items: center;
    }
    .btn_submit input{
        height: 35px;
        padding: 8px;
        border-radius: 8px;
        border: 0.8px solid black;
        font-weight: bold;
        background-color: aliceblue;
        font-size: 12px;
    }
    .btn_submit p{
        background-color: aliceblue;
        border: 0.8px solid black;
        border-radius: 8px;
        display: inline;
        padding: 8px;
        font-weight: bold;
        font-size: 12px;
        height: 15px;
    }
</style>


<h1>Create Article</h1>
<div class="container">
<div class="form">
<%= form_for @article,:url => {:action => 'create'} do |field| %>
<p>
    <label for="">Title : </label>
    <%= field.text_field 'title' %>
</p>
<p>
    <label for="">Author : </label>
    <%= field.text_field 'author' %>
</p>
<p>
    <label for="">Content : </label>
    <div class="text_area">
        <%= field.text_area 'content', size: "40x10" %>
    </div>
</p>
<div class="btn_submit">
        <%= submit_tag "Create" %>
    <p>
        <%= link_to "Back",article_index_path %>
    </p>
</div>
<% end %>
</div>
</div>

app/views/article/show.html.erb
<style>
    .container{
        display: flex;
        text-align: center;
        justify-content: center;
    }
    .data{
        width: 600px;
        display: grid;
        background-color: rgb(210, 210, 210);
        border: 1.5px black solid;
        margin: 15px;
        border-radius: 12px;
        text-align: center;
        padding: 10px 0px;
    }
    .content span{
        display: block;
        font-style: italic;
        padding: 5px;
        font-size: 15px;
        font-weight: 100;
        text-align: center;
    }
    .data p{
        font-size: 15px;
        padding: 3px;
        margin: 0;
    }
    .title{
        display: grid;
        margin: 20px;
    }
    .title h1{
        margin: 0;
    }
    .time{
        margin: 10px;
    }
    .time p{
        font-size: 12px;
        /* display: inline; */
        padding-left: 10px;
        padding-right: 10px;
    }
    .content{
        padding: 15px;
        justify-content: center;
        align-items: center;
        text-wrap: balance;
    }
    .btn{
        padding: 8px;
        margin: 5px;
        display: flex;
        justify-content: space-evenly;
    }
    .btn p{
        display: inline;
        border: solid 1px black;
        border-radius: 5px;
        background-color: aliceblue;
        padding: 5px 10px;
    }
    .btn p a{
        color: black;
        font-size: 15px;
    }

</style>


<div class="container">
    <div class="data">
        <div class="title">
            <h1><%= @article.title.capitalize %></h1>
        </div>
        <div class="content">
            <%= @article.content.capitalize %>
            <span> - by <%= @article.author.capitalize %></span>
        </div>
        <div class="time">
            <p>
                Posted-at : <%= @article.created_at %>
            </p>
            <p>
                Updated-at : <%= @article.updated_at %>
            </p>
        </div>
        <div class="btn">
            <p><%= link_to "Back",article_list_path %></p>
            <p><%= link_to "Edit",{:action => 'edit',:id => @article.id} %></p>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog Article's</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <style>
      body{
        top: 0;
        left: 0;
        margin: 0;
      }
    </style>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: 'navbar' %>
    <br><br>
    <div>
      <%= yield %>
    </div>
  </body>
</html>